### ISSUE TITLE
navigator.language is not overrided

### ISSUE THREAD

**Issue by Siarhei-Yarkavy** [M-Reimer/languageswitch#1]
In the description for this cool add-on I see has avability to override navigator.language but in doesn't work.
Might be this is because https://addons.mozilla.org/ru/firefox/addon/languageswitch/ has only 1.0.3 version but not 1.1?

**Comment by M-Reimer** [comment]
Mozilla delisted my new version. Probably because of the new feature (navigator.language override) that they want to manually review first.

But I don't know what is happening. I wasn't informed about this. So I posted a message to their addon developer mailing list. Let's see what they answer.

**Comment by M-Reimer** [comment]
As Mozilla didn't answer my request, so far, I just released 1.1.1 without any changes. This seems to have worked around the AMO bug. I hope 1.1.1 doesn't get delisted again...

**Comment by neoacevedo** [comment]
Good, it still isn't working.

I tried with Facebook, Twitter, Google, Bing, etc, etc and the language is never overrided.

**Comment by M-Reimer** [comment]
Please provide an example URL.
I currently tried "bing.com". Accessing it with my "default settings" gives me german texts.
Then I used "languageswitch" to switch to "English" and did a "shift + reload". Directly after reloading all texts were english. So works for me.
